### ISSUE TITLE
Create BTree

### ISSUE THREAD

**Issue by HunterBarclay** [KyroVibe/CS321-003-f22-team-08#2]
### Description
Program to create BTrees from given datasets

### Acceptance Criteria:
- [ ] Create a BTree that can store arbitrary objects
- [ ] Can insert and retrieve any object
- [ ] Can store a BTree in the FileSystem and load it after the fact
- [ ] Provides meta information about the tree
- [ ] Can load DNA sub-sequences from GeneBank (.gbk) files
