### ISSUE TITLE
Practice Tasks

### ISSUE THREAD

**Issue by HunterBarclay** [KyroVibe/CS321-003-f22-team-08#4]
### Description
Get used to the scrum flow by creating and finishing a task for adding your information to [README-submission.md](https://github.com/KyroVibe/CS321-003-f22-team-08/blob/master/README-submission.md)

### Acceptance Criteria
- [x] Add Hunter's information to [README-submission.md](https://github.com/KyroVibe/CS321-003-f22-team-08/blob/master/README-submission.md) and follow the scrum process.
- [x] Add Tyler's information to [README-submission.md](https://github.com/KyroVibe/CS321-003-f22-team-08/blob/master/README-submission.md) and follow the scrum process.
- [x] Add Joshua's information to [README-submission.md](https://github.com/KyroVibe/CS321-003-f22-team-08/blob/master/README-submission.md) and follow the scrum process.

**Comment by HunterBarclay** [comment]
@tylerpierce683 Make sure to create the task and stuff as talked about in the [README](https://github.com/KyroVibe/CS321-003-f22-team-08/blob/master/README.md)
